title: "selfdriven Exchange"
description: "Exchanging community value"
baseurl: ""
url: ""
context: "exchange"
repo: "selfdriven-exchange"
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: selfdriven
plugins:
  - jekyll-feed
  - jekyll-seo-tag
